name: "01_IaC_CD"

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - .azuredevops/01-azure-pipelines.yml
      - 01_IaC

pool:
  vmImage: ubuntu-latest

# TO DO:
# ======
# Uncomment the line(s) below and set the required values to run the pipeline
#
#
#
# variables:
#   AZURE_SUBSCRIPTION: '<Your Azure subscription name>'

stages:

- stage: Build
  jobs:
  - job: GenerateArmTemplate
    steps:
    - task: AzureCLI@2
      displayName: "Build Bicep file"
      inputs:
        azureSubscription: '$(AZURE_SUBSCRIPTION)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az bicep install
          cd ./01_IaC
          az bicep build -f Apim.bicep
          cp Apim.json '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: "Publish artifact"
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Release
  jobs:
  - deployment:
    environment: Azure_Apim_Resource_Group
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: "Download artifacts"
            inputs:
              buildType: 'current'
              downloadType: 'specific'
              itemPattern: 'drop/Apim.json'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureCLI@2
            displayName: "Deploy API Management resource"
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              workingDirectory: '$(System.ArtifactsDirectory)/drop'
              inlineScript: |
                az deployment group create -f Apim.json -g rg_demo_apim_festivalms
