# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: "01_IaC_CD"

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build
  jobs:
  - job: BuildBicep
    steps:
    - task: AzureCLI@2
      displayName: "Build Bicep file"
      inputs:
        azureSubscription: 'Microsoft Azure MVP Sponsorship (Igor)(630a091a-3a08-4b05-a9f7-1ee7b784c0ae)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az bicep install
          cd ./01_IaC
          az bicep build -f Apim.bicep
          cp Apim.json '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: "Publish artifact"
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Release
  jobs:
  - deployment:
    environment: Azure_Apim_Resource_Group
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'specific'
              itemPattern: 'Apim.json'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureCLI@2
            displayName: "Build Bicep file"
            inputs:
              azureSubscription: 'Microsoft Azure MVP Sponsorship (Igor)(630a091a-3a08-4b05-a9f7-1ee7b784c0ae)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              workingDirectory: '$(System.ArtifactsDirectory)'
              inlineScript: |
                az deployment group create -f Apim.json -g rg_demo_apim_festivalms
