# Starter pipeline
name: "03_WeatherApi_CD"

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - .azuredevops/03-azure-pipelines.yml
      - 03_WeatherAPI

variables:
  BuildConfiguration: Debug

pool:
  vmImage: windows-latest

stages:

- stage: Build

  jobs:
  - job: BuildApiProject
    steps:
    - task: DotNetCoreCLI@2
      displayName: "Build and package solution"
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
    - script: |
        dotnet tool install --global Swashbuckle.AspNetCore.Cli
        cd 03_WeatherAPI/bin/Debug/net5.0
        swagger tofile --output "$(Build.ArtifactStagingDirectory)/swagger.json" ./WeatherAPI.dll v1
      displayName: "Generate Swagger file"
    - task: PublishBuildArtifacts@1
      displayName: "Publish artifact"
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Release
  jobs:
  - deployment:
    environment: Weather_Api
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: "Deploy API"
            inputs:
              azureSubscription: 'Microsoft Azure MVP Sponsorship (Igor)(630a091a-3a08-4b05-a9f7-1ee7b784c0ae)'
              appType: 'webApp'
              appName: 'igoravl-demo-festivalms'
              package: '$(Agent.BuildDirectory)/**/*.zip'
              deploymentMethod: 'auto'
          - task: apim@5
            displayName: "Update API definition in APIM"
            inputs:
              ConnectedServiceNameARM: 'Microsoft Azure MVP Sponsorship (Igor)(630a091a-3a08-4b05-a9f7-1ee7b784c0ae)'
              ResourceGroupName: 'rg_demo_apim_festivalms'
              ApiPortalName: 'igoravl-apim-dev-brs'
              OpenAPISpec: 'v3'
              Format: 'json'
              Authorization: 'None'
              SwaggerPicker: 'Artifact'
              swaggerartifact: '$(Agent.BuildDirectory)/drop/swagger.json'
              targetapi: 'WeatherAPI'
              pathapi: 'api'
              MicrosoftApiManagementAPIVersion: '2017-03-01'

