# Starter pipeline
name: "03_WeatherApi_CD"

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - .azuredevops/03-azure-pipelines.yml
      - 03_WeatherAPI

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build
  pool:
    vmImage: windows-latest

  jobs:
  - job: BuildApiProject
    steps:
    - script: |
        dotnet build /p:configuration="debug" /p:platform="any cpu" /p:WebPublishMethod=Package /p:PackageFileName="WeatherApi.zip" /p:DesktopBuildPackageLocation="WeatherApi.zip" /p:PackageAsSingleFile=true /p:PackageLocation="WeatherApi.zip" /p:DeployOnBuild=true /p:DeployTarget=Package
        move *.zip $(Build.ArtifactStagingDirectory)
      displayName: 'Run dotnet build'
      workingDirectory: 03_WeatherAPI
    - script: |
        dotnet tool install --global Swashbuckle.AspNetCore.Cli
        cd 03_WeatherAPI/bin/Debug/net5.0
        swagger tofile --output "$(Build.ArtifactStagingDirectory)/swagger.json" ./WeatherAPI.dll v1
      displayName: "Generate Swagger file"
    - task: PublishBuildArtifacts@1
      displayName: "Publish artifact"
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Release
  jobs:
  - deployment:
    environment: Weather_Api
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.DefaultWorkingDirectory)'
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Microsoft Azure MVP Sponsorship (Igor)(630a091a-3a08-4b05-a9f7-1ee7b784c0ae)'
              appType: 'webApp'
              appName: 'igoravl-demo-festivalms'
              package: '$(System.DefaultWorkingDirectory)/**/*.zip'
              deploymentMethod: 'auto'